frr defaults datacenter
hostname leaf-1
log stdout informational
service integrated-vtysh-config
!
interface lo
 ip address 10.0.0.11/32
!
interface eth1
 ip address 10.255.0.1/31
!
interface eth2
 ip address 10.255.0.3/31
!
interface eth3
 ip address 10.1.1.1/24
!
router bgp 65101
 bgp router-id 10.0.0.11
 no bgp ebgp-requires-policy
 neighbor 10.255.0.0 remote-as 65000
 neighbor 10.255.0.2 remote-as 65000
 !
 address-family ipv4 unicast
  network 10.0.0.11/32
  network 10.1.1.0/24
  maximum-paths 2
 exit-address-family
!
