"""Slice 1 persistence foundations (Day 4B1)

Creates the four Slice 1 tables (``devices``, ``configuration_snapshots``,
``configuration_policies``, ``incidents``), the two-stage
``devices <-> configuration_snapshots`` foreign keys (added only after both
tables exist, since they form a cycle — see docs/architecture.md
Section 11.2 and the Day 4B1 binding decisions in CLAUDE.md), the
partial unique index enforcing at most one OPEN incident per fingerprint,
and CHECK constraints for every TEXT-backed enum column, hash format,
occurrence count, and timestamp ordering invariant.

Hand-written, not autogenerated, given the staged FK/constraint ordering
below. Repositories, seeding, and the atomic upsert are not implemented by
this migration alone — they are Day 4B2/4B3 application code; this
revision only creates the schema they will write to.

Revision ID: 0001_slice1_persistence
Revises:
Create Date: 2026-07-18

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
# Kept to 23 characters — alembic_version.version_num is VARCHAR(32).
revision: str = "0001_slice1_persistence"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "devices",
        sa.Column("device_id", sa.Text(), primary_key=True),
        sa.Column("vendor", sa.Text(), nullable=False),
        sa.Column("current_snapshot_id", sa.Text(), nullable=True),
        sa.Column("baseline_snapshot_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.CheckConstraint(
            "updated_at >= created_at", name="ck_devices_updated_at_after_created_at"
        ),
        sa.CheckConstraint("vendor IN ('cisco-ios-xe', 'arista-eos')", name="ck_devices_vendor"),
    )

    op.create_table(
        "configuration_snapshots",
        sa.Column("snapshot_id", sa.Text(), primary_key=True),
        sa.Column("device_id", sa.Text(), sa.ForeignKey("devices.device_id"), nullable=False),
        sa.Column("vendor", sa.Text(), nullable=False),
        sa.Column("raw_config_text", sa.Text(), nullable=False),
        sa.Column("raw_text_hash", sa.Text(), nullable=False),
        sa.Column("normalized_config", postgresql.JSONB(), nullable=False),
        sa.Column("submitted_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.CheckConstraint(
            "raw_text_hash ~ '^[0-9a-f]{64}$'",
            name="ck_configuration_snapshots_hash_format",
        ),
        sa.CheckConstraint(
            "vendor IN ('cisco-ios-xe', 'arista-eos')",
            name="ck_configuration_snapshots_vendor",
        ),
    )
    op.create_index(
        "ix_configuration_snapshots_device_id",
        "configuration_snapshots",
        ["device_id"],
    )

    # Both devices -> configuration_snapshots FKs are added now that both
    # tables exist, resolving the circular reference. Nullable,
    # non-deferrable: the application write order (Device with null
    # snapshot refs -> ConfigurationSnapshot insert -> Device update with
    # snapshot refs) never needs a deferred check.
    op.create_foreign_key(
        "fk_devices_current_snapshot",
        "devices",
        "configuration_snapshots",
        ["current_snapshot_id"],
        ["snapshot_id"],
    )
    op.create_foreign_key(
        "fk_devices_baseline_snapshot",
        "devices",
        "configuration_snapshots",
        ["baseline_snapshot_id"],
        ["snapshot_id"],
    )

    op.create_table(
        "configuration_policies",
        sa.Column("policy_id", sa.Text(), primary_key=True),
        # No FK to devices: seed policies are inserted before any device
        # row exists (architecture.md Section 11.2's seed-after-migration
        # ordering).
        sa.Column("applies_to", sa.Text(), nullable=False),
        sa.Column("required_acls", postgresql.JSONB(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
    )

    op.create_table(
        "incidents",
        sa.Column("incident_id", sa.Text(), primary_key=True),
        sa.Column("fingerprint", sa.Text(), nullable=False),
        sa.Column("device_id", sa.Text(), sa.ForeignKey("devices.device_id"), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("rule_ref", sa.Text(), nullable=False),
        sa.Column("affected_resource", sa.Text(), nullable=False),
        sa.Column("severity", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("evidence", postgresql.JSONB(), nullable=False),
        sa.Column("recommendation", sa.Text(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("occurrence_count", sa.Integer(), nullable=False, server_default="1"),
        sa.CheckConstraint(
            "source IN ('POLICY_VIOLATION', 'DRIFT', 'ANOMALY')", name="ck_incidents_source"
        ),
        sa.CheckConstraint(
            "severity IN ('Critical', 'High', 'Medium', 'Low')", name="ck_incidents_severity"
        ),
        sa.CheckConstraint(
            "status IN ('OPEN', 'ACKNOWLEDGED', 'RESOLVED')", name="ck_incidents_status"
        ),
        sa.CheckConstraint("occurrence_count >= 1", name="ck_incidents_occurrence_count_min"),
        sa.CheckConstraint(
            "fingerprint ~ '^[0-9a-f]{64}$'", name="ck_incidents_fingerprint_format"
        ),
        sa.CheckConstraint(
            "last_seen_at >= created_at", name="ck_incidents_last_seen_after_created"
        ),
    )
    op.create_index("ix_incidents_device_id", "incidents", ["device_id"])
    op.create_index(
        "ux_incidents_open_fingerprint",
        "incidents",
        ["fingerprint"],
        unique=True,
        postgresql_where=sa.text("status = 'OPEN'"),
    )


def downgrade() -> None:
    op.drop_index("ux_incidents_open_fingerprint", table_name="incidents")
    op.drop_index("ix_incidents_device_id", table_name="incidents")
    op.drop_table("incidents")

    op.drop_table("configuration_policies")

    op.drop_constraint("fk_devices_baseline_snapshot", "devices", type_="foreignkey")
    op.drop_constraint("fk_devices_current_snapshot", "devices", type_="foreignkey")
    op.drop_index("ix_configuration_snapshots_device_id", table_name="configuration_snapshots")
    op.drop_table("configuration_snapshots")

    op.drop_table("devices")
