frr defaults datacenter
hostname spine-2
log stdout informational
service integrated-vtysh-config
!
interface lo
 ip address 10.0.0.2/32
!
interface eth1
 ip address 10.255.0.2/31
!
interface eth2
 ip address 10.255.0.6/31
!
router bgp 65000
 bgp router-id 10.0.0.2
 no bgp ebgp-requires-policy
 neighbor 10.255.0.3 remote-as 65101
 neighbor 10.255.0.7 remote-as 65102
 !
 address-family ipv4 unicast
  network 10.0.0.2/32
 exit-address-family
!
