frr defaults datacenter
hostname leaf-2
log stdout informational
service integrated-vtysh-config
!
interface lo
 ip address 10.0.0.12/32
!
interface eth1
 ip address 10.255.0.5/31
!
interface eth2
 ip address 10.255.0.7/31
!
interface eth3
 ip address 10.1.2.1/24
!
router bgp 65102
 bgp router-id 10.0.0.12
 no bgp ebgp-requires-policy
 neighbor 10.255.0.4 remote-as 65000
 neighbor 10.255.0.6 remote-as 65000
 !
 address-family ipv4 unicast
  network 10.0.0.12/32
  network 10.1.2.0/24
  maximum-paths 2
 exit-address-family
!
